-- migrations/albums.sql
-- Insert all albums data

INSERT INTO albums (id, catalogue, name, cover_url, production_date, release_date, artist_id, credit, description, tracks) VALUES 
(1, '00040101', 'Charlotta', 'https://storage.googleapis.com/ip-public-bucket1/Charlotta/1_CHARLOTTA.png', 'May 1, 2005', 'October 3, 2010', 1, 'All Sound & Composition: Roderick Shoolbraid.<br>Cover Art, Photography & Design: Roderick Shoolbraid.<br> &copy;All Rights Reserved.', 'The debut ambient electronic album by Roderick Shoolbraid, written in a span from 2003 to 2005. Released in 2010. A soundtrack for a dream, and a film that never was.', 8),
(2, '00040102', 'Objects & Particles', 'https://storage.googleapis.com/ip-public-bucket1/Objects-and-Particles/2_OBJECTS-PARTICLES.png', 'March 1, 2006', 'October 10, 2010', 1, 'All Sound & Composition: Roderick Shoolbraid.<br>Cover Art, Photography & Design: Roderick Shoolbraid.<br> &copy;All Rights Reserved.', 'Between "Charlotta" & "Glass City of Us" (2004-6), this darker album explored minimal ambient music. It used noise, line hum, record skips, and drone reverbs. Inspired by the idea that objects in math, physics, & chemistry have their own music, if we listen closely.', 6),
(3, '00040103', 'Glass City of Us', 'https://storage.googleapis.com/ip-public-bucket1/Glass-City-of-Us/3_GLASS-CITY-OF-US.png', 'April 1, 2005', 'October 6, 2010', 1, 'All Sound & Composition: Roderick Shoolbraid.<br>Cover Art, Photography & Design: Roderick Shoolbraid.<br> &copy;All Rights Reserved.', 'This album became the sequel to "Charlotta", composed and engineered over a 2 year period from 2003-2005, finished in the middle of 2005. The concept of "The City" emerged through the rough romantic plot of two people in a massive futuristic city, that seems dwarfed by the sentiments by them both.', 6),
(4, '00040104', 'New Domes of Earth', 'https://storage.googleapis.com/ip-public-bucket1/New-Domes-of-Earth/4_NEW-DOMES.png', 'May 15, 2005', 'October 19, 2010', 1, 'All Sound & Composition: Roderick Shoolbraid.<br>Cover Art, Photography & Design: Roderick Shoolbraid.<br> &copy;All Rights Reserved.', 'Music for visions of the future.', 6),
(5, '01040105', 'Natura', 'https://storage.googleapis.com/ip-public-bucket1/Natura/5_NATURA.png', 'March 15, 2022', 'March 22, 2022', 1, 'All Sound & Instruments: Roderick Shoolbraid. <br>Painting & Album Cover Design: Roderick Shoolbraid. <br>&copy;All Rights Reserved.', 'An open letter of love and admiration for the natural world.', 9),
(6, '01040106', 'Outer Corners', 'https://storage.googleapis.com/ip-public-bucket1/Outer-Corners/6_OUTER-CORNERS.png', 'February 15, 2022', 'March 25, 2022', 1, 'All Sound & Composition: Roderick Shoolbraid.<br>Cover Art, Photography & Design: Roderick Shoolbraid.<br> &copy;All Rights Reserved.', 'Music for the stars and beyond. Started in late 2021, completed in 2022.', 7),
(7, '01040107', 'Nonagon', 'https://storage.googleapis.com/ip-public-bucket1/Nonagon/7_NONAGON.png', 'May 15, 2022', 'June 14, 2022', 1, 'All Sound, production & Composition: <br>Roderick Shoolbraid <br> Cover design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'Lines drawn by field recordings, manipulated and accompanied by guitars & bass. Coloured in by synths and reverb to show a space of the beauty of geometry. Sound sources from: 1996-7, 2003-15. Compiled and finished in summer 2022.', 9),
(8, '01040108', 'Ambient Garden One', 'https://storage.googleapis.com/ip-public-bucket1/Ambient-Garden-One/8_AMBIENTGARDENONE.png', 'June 22, 2022', 'June 22, 2022', 1, 'All Sound, production & Composition: <br>Roderick Shoolbraid <br> Cover design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'A curated collection of some favourite pieces from the present discography. Spanning 20 years 2002-2022, this exposition showcases the work from a variety of different artistic perspectives: Electronica, Drone, Minimalism, Polytonality and Free Jazz. <br>One is always a summary of influences. And in this compilation it is evident - an open letter to the history of electronic, electro-acoustic music and musique concrète. The appreciation for the natural world and Its interplay with the Astral.', 14),
(9, '01040109', 'Music for Seven Structures', 'https://storage.googleapis.com/ip-public-bucket1/Music-For-Seven-Structures/9_7STRUCTURES.png', 'June 1, 2022', 'June 28, 2022', 1, 'All Sound & Composition: Roderick Shoolbraid<br> Cover design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'A simple minimal album exploring the images of places and structures that came to mind, while designing & demoing the synth patches created for Nonagon. Written from May to June 2022.', 7),
(10, '01040110', 'Inner Moments of Light', 'https://storage.googleapis.com/ip-public-bucket1/Inner-Moment-of-Light/10_INNER-MOMENTS.png', 'November 15, 2015', 'July 9, 2022', 1, 'All Music & Sound: Roderick Shoolbraid <br> Cover Design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'A collection or curation of assorted tracks from 2003-2015. With some source files going back as far as 1996-7. Organized finally in a little volume of what I like to think of as sacred or holy music, music or sound for meditation into specific spaces, or at least it is what it is for me. Everyone will have their own experience of the ambient medicinal sounds, finding itself roots in Minimalism, Drone, Noise, & Lo Fi. This was my original intent behind the contemplative sound, and music I created, whether I am successful, I leave that in your hands and your mind.', 9),
(11, '01040111', 'Nocturnes & Reveries', 'https://storage.googleapis.com/ip-public-bucket1/Nocturnes-and-Reveries/11_NOCTURNES-REVERIES.png', 'August 23, 2022', 'September 3, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid. <br>Cover Design: Roderick Shoolbraid. <br>Painting: <em>"Nocturnes"</em> - Roderick Shoolbraid. <br> &copy;All Rights Reserved.', 'A collection of 15 compositions, experiments and musings; all centred around night scenes, dreams, the mystical, and the subconscious. Using more challenging approach to scales and harmony, the album is influenced by Olivier Messiaen, György Ligeti, Gurdjieff, Sufi and Eastern Music.', 15),
(12, '01040112', 'Prefabrication', 'https://storage.googleapis.com/ip-public-bucket1/Prefabrication/12_PREFABRICATION.png', 'December 15, 2022', 'January 24, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid <br> Cover Design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', '"Prefabrication" is an album that builds on the concept of Music for Seven Structures, it uses one central melodic passage interpreted from 10 different viewpoints.<br>The motif is modified based on multiples of 4 and pitch in octaves, creating a library of relative sounds. These sounds are arranged together in patterns and structures using a fixed tempo of 120 bpm throughout the albums 10 pieces.<br> Predetermined edits and automation of effects are done to a grid to create an environment of chance. After this "prefabrication" stage, a more detailed finish is applied , drawing from the lexicon of modern electronica and IDM.<br>The album is intended to be a collection of remixes on the subject of the experience of being inside a simple minimalist designed building.', 10),
(13, '01040113', 'Vagary', 'https://storage.googleapis.com/ip-public-bucket1/Vagary/13_VAGARY.png', 'January 15, 2023', 'February 11, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid <br> Cover Design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'A series of 8 tone poems on the inward experience of my healing journey.  Written over a course of 6 months from 2022, to the following year.', 8),
(14, '01040114', 'Amsterdam Concreet', 'https://storage.googleapis.com/ip-public-bucket1/Amsterdam-Concreet/14_AMSTERDAM-CONCREET.png', 'February 15, 2023', 'February 20, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid <br>Location recording: (Exhibit A,B,C1-3): <br>Tanya Slingsby & Dylan Armour <br>Principal Cover photography: Dylan Armour <br> Cover Design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', '"Found Sound" and location recordings from Amsterdam, processed and layered. Compiled in collages and atmospheres, as a portal to introspective travel.', 9),
(15, '01040115', 'Watercolours for Friends', 'https://storage.googleapis.com/ip-public-bucket1/Watercolours-for-Friends/15_WATERCOLOURS.png', 'March 20, 2023', 'March 24, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid <br> Cover Design: Roderick Shoolbraid <br> Watercolour Painting: "Forest Lake" 2023: Roderick Shoolbraid', 'This album was a response creatively to the large project and emotionally requiring: VAGARY. WATERCOLOURS FOR FRIENDS was a return to a more simple melodic structure and production values of my first releases. <br>With that in mind, I used sound sources and instruments from my first few years at sound design collage from 2002-3, with a view to create a minimalist palette. <br>A wonderful friend had remarked that though she appreciated the foreboding, emotional gravity and unsettling nature of VAGARY and other work, it was pieces like "Spherical" of NONAGON that she liked. As she could do other things and be in the space with the music.<br>These comments greatly influenced the composition and structure of the sound, treating them like large rooms of watercolour paintings that one could be inside.', 7),
(16, '01040116', 'Postcards from Old Sounds', 'https://storage.googleapis.com/ip-public-bucket1/Postcards-From-Old-Sounds/16_POSTACARDS-OLD-SOUNDS.png', 'April 20, 2023', 'April 30, 2023', 1, 'All Sound & Composition: Roderick Shoolbraid <br> Cover Design & Photography: Roderick Shoolbraid <br>&copy;All Rights Reserved.', '"Postcards from Old Sounds" is a continuation from "Watercolours For Friends" in its approach to harmony and sound design. <br>Using a long form minimalist structure, the idea is: that these small sounds from the early 2000s are carried forward into the present palette and shaped with modern tools. <br>Telling us stories of where they have been. It was written in tandem with "Watercolours.." in the spring of 2023.', 5),
(17, '01040117', 'Sakura', 'https://storage.googleapis.com/ip-public-bucket1/Sakura/17_SAKURA.png', 'June 15, 2023', 'June 19, 2023', 1, 'All Sound & Instruments: Roderick Shoolbraid. <br> Cover Design: Roderick Shoolbraid', 'One starts with no real intentions sometimes, and after awhile the idea formulates and direction emerges. Such was the case with "SAKURA". <br>Written during April and May of this year, 2023, the materials gathered from improvised sessions were interludes between the walks along the seaside, where the blossoms fell from the trees.<br>All of this reminded me of the visit I had to Japan for 6 months in 1998-1999. I had been listening to a lot of city pop over the winter, and thinking about my good late friend Peter Stufano. I decided to use all of this as a starting point.<br>I had a small library of samples of my friend playing several instruments: tabla, dumbek, kalimba, and flute; and these became the sources in sampler instruments for the melodies. <br>I used location recordings of the walks along the sea and record skips from the end of the city pop & Japanese jazz records I was listening to as a backdrop. <br>The piano samples are from public outdoor instrument recorded a couple years ago, and the guitar work was completed this month.These are the materials used to create the sonic paintings of my memories, please enjoy & thank you for listening.-Roderick', 7),
(18, '01040118', 'Poem for a Homeworld', 'https://storage.googleapis.com/ip-public-bucket1/Poem-For-A-Homeworld/18_POEM-HOMEWORLD.png', 'October 20, 2023', 'October 25, 2023', 1, 'All Sound & Instruments: Roderick Shoolbraid<br> Voice sample on track #1: Lynn Demers<br> Voice sample on track #7: Lovina Lakatua <br>Vocal on track #7: Ruby Lakatua<br>Cover Design: Roderick Shoolbraid<br> &copy;All Rights Reserved.', 'A cascade of experiences, a free fall into pulp science fiction of singular memory, set against 1990s electronic music''s landscape & language. <em>What is the plot summary for our protagonist? </em>Only the environments know. <br>Written over 7 months pulling from reservoirs of old and new sounds: <em>"Poem for a Homeworld"</em> has a history of its own. <br>Where are we in the index of portals? "Have I not been here before?" asks the lone traveller as all paths lead back to the beginning of the contemplations: <br><br>"Am I alone? If I am alone in the universe, am I then not alone? If I am held in the embrace of the expanse of the universe?" <br><br>These are the questions and revelations of our story, painted in the colours and reference of nostalgia.A lament from a distant future, a chaos of remembrance; an understanding that all time exists at once, on the cusp of the Void. A narrative set against the abstracted lexicon of 90s ambient drum & bass on a bed of watercolours of experiments. Completed by the fall of 2023.', 15),
(19, '01040119', 'Rhombus', 'https://storage.googleapis.com/ip-public-bucket1/Rhombus/19_RHOMBUS.png', 'December 15, 2023', 'January 1, 2024', 1, 'All Sound & Music: Roderick Shoolbraid<br>Words: Roderick Shoolbraid <br>*except for "Art District" : Lovina Lakatua<br>Vocal Samples All other tracks: Roderick Shoolbraid<br>"Art District" :<br>Vocal sample provided by: Lovina Lakatua<br>"A window is a Friend of Rain" :<br>Vocal sample provided by: Lovina & Ruby Lakatua<br>Cover:<br>Original Art: Kristin Shoolbraid<br>Processing and Cover design: Roderick Shoolbraid<br>&copy;All Rights Reserved.', 'Written in 2023, "Rhombus" was a brief break away from "Poem For a Homeworld". It revealed itself a collection of sounds distilled into larger ideas. <br>I had been learning about and working with AI, and the following assortment of music reflects this exploration, and the deeper meaning behind it all. <br>It is written in lamenting tone, similar to "Poem...", but its more immediate in its time scale and locale. <br>A strange new future awaits us I am sure, these are the meditations on those themes.', 10),
(20, '01040120', 'Vignettes of Clouds', 'https://storage.googleapis.com/ip-public-bucket1/Vignettes-of-Clouds/20_Vignettes-of-Clouds.png', 'April 15, 2024', 'May 23, 2024', 1, 'All Sound & Instruments : Roderick Shoolbraid <br>Cover Design: Roderick Shoolbraid <br> &copy;All Rights Reserved.', 'Inconsistently written over a period of 14 months (from: March 2023 to May 2024), - a collection of out-takes, or experiments; eventually became the foundation for a series of essays on the subject of ''clouds'',and our relationship with them. <br>Halfway through the album, adjunctive compositions emerged and the overall thesis for the curation was complete. <br><br>There are different routes to the same conclusion, that the mesmerizing stories of our friends of the sky hold a sacred truth, and a portal to a great understanding.', 12),
(21, '01040121', 'JIKAN | Original Soundtrack', 'https://storage.googleapis.com/ip-public-bucket1/Jikan/21_JIKAN.png', 'April 15, 2016', 'September 30, 2024', 1, 'All Sound, Composition & Music: Roderick Shoolbraid <br> &copy; All rights reserved', 'Original Soundtrack to the 35 minute 2016 film, "JIKAN" by Lynn Demers.', 7),
(22, '01040122', 'Apocrypha', 'https://storage.googleapis.com/ip-public-bucket1/Apocrypha/APOCRYPHA_Resize.png', 'January 18, 2025', 'January 18, 2025', 1, 'All Sound, Composition & Music: Roderick Shoolbraid <br> &copy; All rights reserved', 'There is a stillness in the wind, and the boat rounds the misty corner.  There is a quickening to the current, and the song of the water lapping up against the hull, starts to sing louder.  <br>A shard of light appears through the clouds.  A golden light and yet we know its not the sun.<br>There is an understanding before one understands one has understood, and there is no container for the impression.  I wonder how the mathematics feel about that.  <br>We are on the cusp of something and yet in the void.   <br>This Album was written over a long period of time, from 2023 until now. However there are parts which date back years, or even decades.  <br>It is a solace to have this idea come to its completion.  <br>I invite you to listen to the essays on the satori of the machines.', 15),
(23, '01040123', 'Ambient Garden Two', 'https://storage.googleapis.com/ip-public-bucket1/Ambient-Garden-Two/AMBIENTGARDENTWOsm-v2.png', 'February 13, 2025', 'February 13, 2025', 1, 'All Sound, Composition & Music: Roderick Shoolbraid <br> &copy; All rights reserved', 'In this second curation of Roderick''s work, the compilation is comprised from the 9th to 22nd album; between the dates: June 2022 to January 2025. <br>These 14 albums, draw and expand on the lexicon of the previous. Some more difficult and adventurous, others more simplistic, or sonorous; and some larger ambitious concept projects- Needless to say the core compositional approach and themes remains the same: Nature and the cosmos, and our social contract with it. <br>This curation hopes to bring a central tonal idea as well as a celebration of the collected ideas across the released material over the last 3 years.', 14),
(24, '01040124', 'Utopian', 'https://storage.googleapis.com/ip-public-bucket1/UTOPIA/UTOPIAN-coverFINAL.png', 'May 29, 2025', 'May 29, 2025', 1, 'All Sound, Composition & Music: Roderick Shoolbraid <br> &copy; All rights reserved', 'An array of collections: Retrospective and Personal. <br> We all have moments where we are brought into the presence of our ''belief''; and then we are shown the Future. <br>It is in these moments that with the grand vision and vantage we can see clearly and it only forms a lament of mist on the windows of our history, hardened to frost by Time. <br>Every moment is a beautiful thing, and this is our dream in our Utopia. <br>Loops of noises, fluids of guitars, beats of old sounds... Linear timelines of thought at diagonal intersections, forms the Lattice of the conversations. <br>Written over the first part of 2025.', 8)
ON CONFLICT (id) DO UPDATE SET
  catalogue = EXCLUDED.catalogue,
  name = EXCLUDED.name,
  cover_url = EXCLUDED.cover_url,
  production_date = EXCLUDED.production_date,
  release_date = EXCLUDED.release_date,
  artist_id = EXCLUDED.artist_id,
  credit = EXCLUDED.credit,
  description = EXCLUDED.description,
  tracks = EXCLUDED.tracks,
  updated_at = CURRENT_TIMESTAMP;